config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, except: :create

  resources :snacks do
    resources :ratings
  end

  root 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :snacks
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :snack
  belongs_to :user

  validates :mark,
    presence: true,
    numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 5 }

  validates :user, :snack,
    presence: true

  validates :user_id,
    uniqueness: { scope: :snack_id }

end

app/models/snack.rb
class Snack < ActiveRecord::Base
	belongs_to :category
	has_many :ratings


	validates :brand, :adress, presence: true



	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150>"}

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ratings
  has_many :snacks, :through => :ratings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    before_filter :authenticate_user!

    before_filter :get_snack

  def new
    @rating = @snack.ratings.new
  end

  def create
    @rating = @snack.ratings.new rating_params
    if @rating.save
      flash[:success] = "Rate successfully created"
      redirect_to snacks_path(page: params[:page])
    else
      render :new
    end
  end


  def edit
    @rating = @snack.ratings.find(params[:id])
  end

  def update

    @rating = @snack.ratings.find(params[:id])
    if @rating.update_attributes rating_params
      flash[:success] = "Rate successfully updated"
      redirect_to snacks_path(page: params[:page])
    else
      render :edit
    end
  end

  private

    def rating_params
      params.require(:rating).permit(:mark).update(user: current_user)
    end

    def get_snack
      @snack =  Snack.find(params[:snack_id])
    end
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
   before_filter :authenticate_user!, except: [:index, :show]

  def new
    @snack = Snack.new
  end

  def index
  	@snacks = Snack.page(params[:page]).per(6)
  	@categories = Category.all
  end

  def show
  	@snack = Snack.find(params[:id])
  end

  def edit
    @snack = Snack.find(params[:id])
  end

  def update
    @snack = Snack.find(params[:id])
    if @snack.update_attributes snack_params
      flash[:success] = "Snack successfully updated !"
  	  redirect_to @snack
    else
      render :edit
    end
  end

  def create
  	@snack = Snack.new snack_params
    if @snack.save
      flash[:success] = "Snack successfully created!"
      redirect_to snack_path(@snack)
    else
      render :new
    end
  end

  def destroy
    Snack.find(params[:id]).destroy
    flash[:danger] = "Snack deleted :("
    redirect_to action: :index
  end

  private

  def snack_params
     params.require(:snack).permit(:brand, :adress, :category_id, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  before_action only: [:edit, :update] do
    params[:part] ||= 'password'
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = current_user
  end

  def update
  	@user = User.find(current_user.id)
    if update_user
      flash[:success] = "#{user_params.key?(:password) ? 'Password' : 'Profile'} successfully updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
  	@user = User.find(current_user).destroy
  	flash[:notice] = "Account deleted."
  	redirect_to root_path
  end

  private

  def update_user
    if user_params.key?(:password)
      @user.update_with_password user_params
    else
      @user.update_attributes user_params #update_attribute method skip the validations
    end
  end

  def user_params
     params.require(:user).permit(:email, :name, :current_password, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user)
			gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
			gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=150"
			image_tag(gravatar_url, alt: user.email)
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
  def update_rating_btn(user, snack)
    if current_user
      Rating.where(user_id: current_user.id, snack_id: snack).exists?
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">

<head>
	<title>SnackandCo</title>

	<meta name="viewport" content="width=device-width, initial-scale=1">

	<%= stylesheet_link_tag'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyDVmavr21JzqkX2LK2G0uriwjIJs0jnlU0" %>
	<%= javascript_include_tag 'application','data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>

<body>

	<%= render 'layouts/shared/menu' %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
			<%= render 'layouts/shared/messages' %>

      <%= yield %>

    </div>
  </div>
</div>

</body>

</html>

app/views/layouts/shared/_menu.html.erb
 <nav class="navbar navbar-inverse navbar-static-top">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Side pro</a>
  </div>
  </ul>
    </li>
  </ul>
    <form class="navbar-form navbar-left">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  <ul class="nav navbar-nav navbar-right">
      <li><a href="/">Home</a></li>
    <% if current_user %>
        <li>
        <%= link_to "Profile", user_path(current_user) %>
        </li>
        
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            Log out
          <% end %>
        </li>

   <% else %>
    <li>
    <%= link_to new_user_session_path do %>
        Login
        <% end %>

    <% end %>
      </li>
  </ul>
    </ul>

  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/shared/_messages.html.erb
 <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

app/views/pages/home.html.slim
h1 J'ai faim

div id="map"

.row
	= link_to 'Voir tous les snacks', snacks_path, class: "btn btn-default btn-lg btn-block"

app/views/ratings/edit.html.slim
h1 Modifier la note

= simple_form_for @rating do |f|
  = f.input :snack_id, as: :hidden
  = f.input :mark, as: :select, collection: [1, 2, 3, 4, 5]
  = hidden_field_tag :page, params[:page]
  = f.button :submit

app/views/ratings/new.html.slim
h1 Noter le Snack

= simple_form_for [@snack, @rating] do |f|
  = f.error_messages
  = f.input :mark, as: :select, collection: [1, 2, 3, 4, 5]
  = hidden_field_tag :page, params[:page]
  = f.button :submit

app/views/snacks/edit.html.slim
h1 Modifier le snack

= simple_form_for @snack do |f| 
	= f.input :brand, placeholder: "Nom du restaurant"
	= f.input :adress, placeholder: "Adresse du restaurant", input_html: { id: 'geocomplete'}
	= f.association :category 
	= f.input :image, as: :file 
	= f.button :submit 

= link_to 'Supprimer', snack_path, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure ?'}
= link_to 'Annuler', snacks_path

app/views/snacks/index.html.slim
h1 Liste des snacks

- @snacks.each do |snack|
		= link_to  snack_path(snack) do
			- if snack.category
					.row class="article"
						.col-md-2 class="snack_img" style="background-image: url(#{snack.image.url})"
						.col-md-8
							div 
								h4 = snack.brand
								h5 class="address"
									= snack.adress
								.label.label-info= snack.category.name
						.col-md-2
							h3 Notes
							= snack.ratings.average(:mark)
							.row
								.col-md-12
									-if update_rating_btn(current_user, snack)
									 	= link_to 'Modifier ma note', edit_rating_path(Rating.where(user_id: current_user.id, snack_id: snack.id).first, page: params[:page]), class: "btn btn-primary"
									-else
										= link_to 'Je note', new_rating_path(:snack_id => snack.id, page: params[:page]), class: "btn btn-info"
								
							
.row
	.col-md-12.text-center
		= paginate @snacks, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-md	"
.row
	.col-md-12.text-center
		= link_to 'Ajouter un resto', new_snack_path, class: "btn btn-success btn-lg"

app/views/snacks/new.html.slim
h1 Ajoutez un snack

= simple_form_for @snack do |f|
  = f.input :brand, placeholder: "Nom du restaurant" 
  = f.input :adress, placeholder: "Adresse du restaurant", input_html: { id: 'geocomplete'}
  = f.association :category
  = f.input :image, as: :file 
  = f.button :submit 

= link_to 'Revenir à la liste', snacks_path

app/views/snacks/show.html.slim
h1 Affichage d'un snack

= image_tag @snack.image(:thumb)
p
  h2 = @snack.brand 
p 
  = @snack.adress
p
  = link_to 'Modifier', edit_snack_path, class: 'btn btn-info'
p
  = link_to 'Revenir à la liste', snacks_path

app/views/users/edit.html.slim
h1 Modifier votre profil

= simple_form_for @user do |f|
    = f.input :name, label: 'Pseudo', placeholder: 'Choisissez votre pseudo'
    = f.input :email 
    = f.button :submit 
end

h2 Modifier le mot de passe 
		
= simple_form_for @user do |f|
		= f.input :current_password
		= f.input :password, label: 'New password'
		= f.input :password_confirmation
		= f.button :submit 
end
		
= link_to 'Supprimer le compte', user_path, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' }
p
  = link_to 'Retour au profil', user_path

app/views/users/index.html.slim
h1 Tous les users

	

app/views/users/show.html.slim
div class="row"
	div class="col-md-offset-5"
		= gravatar_for @user

div class="row"
	div class="col-md-offset-5"
		h1 
			= current_user.name 

div class="row"	
		= link_to 'Editer mon profil', edit_user_path, class: "btn btn-default btn-lg btn-block" 
br
div class="row"	
		= link_to 'Snacks favoris', snacks_path, class: "btn btn-default btn-lg btn-block" 